### ISSUE TITLE
Native forced host support

### ISSUE THREAD

**Issue by astei** [VelocityPowered/Velocity#116]
Basically, add hosts that can direct to a specified set of initial connection servers that can be configured in `velocity.toml` as follows:

```toml
[forced-hosts]
"ftb.example.com" = ["ftb-lobby-1", "ftb-lobby-2"]
```
