### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by Proximyst** [VelocityPowered/Velocity#368]
A Docker image should be provided to easily use a dockerised set up.

It would be very useful for folks like me who don't want to have SQL servers on their host machines and still keep the single command up/down of a stack (i.e. `docker-compose`).

**Comment by astei** [comment]
I'm open to it but it'd be a low priority for me right now. (I'm already failing to cut releases on time, adding the additional complication of producing and pushing Docker images is a bit much.)

**Comment by mikroskeem** [comment]
In my opinion, there can rarely be any Docker images that will fit for all use-cases with Minecraft related projects. You're probably better off doing something like this:

```yaml
version: '2.4'

services:
  proxy:
    image: adoptopenjdk:11-jre-hotspot
    restart: unless-stopped
    init: true
    command: java -jar /proxy/velocity.jar
    working_dir: "/proxy"
    volumes:
      - ".:/proxy"
```
